### ISSUE TITLE
Add a version tag

### ISSUE THREAD

**Issue by stephenmcm** [Zazama/silverstripe-phonify#2]
Hi @Zazama 

Could you please add a version tag/release for this module? It makes using it in projects safer as general users (like myself) don't have to worry about new commits to master potentially breaking user code. 
Thanks in advance!

**Comment by Zazama** [comment]
Is it correct that https://github.com/Zazama/silverstripe-phonify/releases/tag/1.0.0 fixes this issue? (Never worked with packagist before)

**Comment by stephenmcm** [comment]
Yep, that works perfectly in packagist:
https://packagist.org/packages/zazama/silverstripe-phonify
Thanks again!
